version: '3.8'

services:
  app:
    build: .
    container_name: fastapi-app
    ports:
      - "8000:8000"
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DB=fastapi
      - MONGO_USER=admin
      - MONGO_PASSWORD=admin123
      - SECRET_KEY=${SECRET_KEY:-change-this-secret-key-in-production}
      - DEBUG=true
    depends_on:
      - mongodb
    volumes:
      - ./app:/app/app  # For development hot-reload
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - fastapi-network

  mongodb:
    image: mongo:7.0
    container_name: fastapi-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
      - MONGO_INITDB_DATABASE=fastapi
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - fastapi-network

  mongo-express:
    image: mongo-express:latest
    container_name: fastapi-mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin123
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    depends_on:
      - mongodb
    networks:
      - fastapi-network

volumes:
  mongodb_data:

networks:
  fastapi-network:
    driver: bridge